Skip auto updates if inst.updates is given
rhinstaller/anaconda pull request #2780
Opened 2020-08-12 01:37 UTC by cheese

Anaconda tried to load updates image from both where specified by inst.updates and
the default path in repo. But user expects the one specified by inst.updates should
take effect.

What even worse is when repo is loaded from disk, loading updates from network and
disk are triggered by different udev rules and there is raise condition. Updates
from repo default path may override what user specified in inst.updates.

This change will skip loading updates from repo when inst.updates is given.

2020-08-12 13:18 UTC, jkonecny12 commented
Jenkins, it's ok to test.

2020-09-03 08:58 UTC, jkonecny12 requested changes
Also we should look on ``OEMDRV``, I think we are using this to load updates_images too so the same logic should be applied there.

2020-09-03 08:58 UTC, jkonecny12 commented on dracut/anaconda-lib.sh
> +            [ -n "$product" ] && unpack_updates_img $product /updates
I don't think updates images should be skipped based on ``inst.updates`` kernel param.

Their are basically the same but product image is specialized on rebranding so it shouldn't be excluded based on updates_image.

2020-09-03 11:19 UTC, jkonecny12 commented
I would just make a small modification to exclude the product.img from the `if` condition.

Optional is to investigate the OEMDRV but even without that it's fine by me.

2020-09-03 15:15 UTC, VladimirSlavik requested changes
I can confirm that the patch as presented works as described. However, I agree with @jkonecny12 that the product image should not be excluded. Updates are a debug/devel thing, while product is meant for regular use on non-code parts of the environments. That isn't too big of a change anyway :-)

The OEMDRV thing still need additional investigation.

2020-09-04 08:36 UTC, jkonecny12 commented
In that case @cheese please change the condition to include only updates image and I think we should be ready for merge. ;)

2020-09-04 09:30 UTC, cheese commented
If auto loading of product.img is kept, then my use case is not fulfilled. In my use case, image specified with inst.updates is the new version of product.img. I want only the data from inst.updates.

If loading default product.img is kept, we should make sure what from inst.updates is overriding. So we should figure out a complete solution other than just this patch.

2020-09-04 11:16 UTC, VladimirSlavik commented
I did not know, so I ran a quick test - looks like the order in which the images are applied is:

1. `inst.updates=`
2. `product.img`
3. `updates.img`

To me that seems just wrong. I would expect the boot option image to be applied at the end of the list. It's the most accessible one, and sees most debugging use where one wants to override everything.

I have no idea what are the considerations for backwards compatibility here.

2020-09-07 08:46 UTC, jkonecny12 commented
> I have no idea what are the considerations for backwards compatibility here.

That's fine. Updates images are used specifically for debugging purposes so the ordering should not matter. I agree that the ordering is not good.

@cheese, what do you think about merging this with the moved ``if`` as discussed above and we can look on adjusting order to this:

- product.img
- updates.img

Whould that work for your issue?

2020-09-07 08:48 UTC, jkonecny12 commented
Another possibility is to introduce new boot option to avoid loading of product image but I would like to avoid that if possible.

2020-09-09 10:27 UTC, VladimirSlavik commented
I'd like to add that since you want something to be not overwritten by `product.img`, you can use `updates.img` in the repo, right now.

Alternatively, maybe try applying the `inst.updates` image after these? I'm not sure if this could work, but maybe it's the fastest compromise for now:

```
        if [[ -n ${anac_updates} ]]; then
            updates_boot=$(fetch_url $anac_updates 2> /tmp/product_err)
            [ -z "$updates_boot" ] && debug_msg $(cat /tmp/updates_boot_err)
            [ -n "$updates_boot" ] && unpack_updates_img updates_boot /updates
        fi
```

`anac_updates` should be set earlier when `inst.updates` is handled, or so I believe.

2020-10-06 10:28 UTC, VladimirSlavik commented
Looks like this is another piece for the graveyard collection...

2020-10-08 10:27 UTC, jkonecny12 commented
@cheese is this patch still interesting to you or we can close it?

2020-10-08 12:02 UTC, cheese commented
This is actually a minor case. I don't have time to work out a better patch for now.

2020-10-08 12:02 UTC, closed without merging