Remove the support for changing the log level
rhinstaller/anaconda pull request #2864
Opened 2020-09-21 12:28 UTC by poncovka

There is no handler that allows to change its log level. The last one was the
file handler for /tmp/packaging.log. Since the commit a2ae719, all handlers
have their log levels set to DEBUG all the time.

Remove the `loglevel` option.

**TODO:**
- [ ] Show a warning for the `--level` option of the `logging` kickstart command.

2020-09-21 15:00 UTC, VladimirSlavik approved these changes
Looks good to me. Thank you!

2020-09-23 11:54 UTC, poncovka commented
Jenkins, test this please.

2020-09-23 13:14 UTC, jkonecny12 approved these changes
Looks good to me so far ;). Thanks for this work!

2020-09-23 13:15 UTC, jkonecny12 reviewed
Removing Approve flag because this is just a Draft still.

2020-10-01 11:06 UTC, poncovka commented
Blocked by pykickstart.

2020-10-02 09:31 UTC, jkonecny12 approved these changes
You have my ACK here. Thanks!

2020-10-02 10:15 UTC, poncovka commented
Jenkins, test this please.

2020-10-02 12:50 UTC, jkonecny12 requested changes
Otherwise you can't merge this.

2020-10-02 12:50 UTC, jkonecny12 commented on anaconda.spec.in
> +%define pykickstartver 3.31-1
Please this should be ``3.30`` version.

2020-10-02 13:04 UTC, poncovka commented on anaconda.spec.in
> +%define pykickstartver 3.31-1
The fix hasn't been released yet.

2020-10-02 13:08 UTC, jkonecny12 commented on anaconda.spec.in
> +%define pykickstartver 3.31-1
my bad, I'm blind

2020-10-02 13:08 UTC, jkonecny12 approved these changes

2020-11-16 11:55 UTC, poncovka commented
Rebased. I will open another pull request for the kickstart command.

2020-11-16 12:22 UTC, merged