Create a new configuration option proxy
rhinstaller/anaconda pull request #2877
Opened 2020-09-30 10:51 UTC by poncovka

Use the new configuration option `proxy` instead of the cmdline option.

Move the code that sets up the proxy environmental variables into a new
function `set_up_proxy_variables` in startup utils.

2020-10-01 09:05 UTC, poncovka commented
Jenkins, test this please.

2020-10-02 09:28 UTC, jkonecny12 requested changes
Could you please explain me the reasoning behind this. I can't image a reason to have configuration option for proxy settings because proxy is dependent on where the computer is placed and not about by what you are doing the installation.

2020-10-02 13:13 UTC, poncovka commented
In progress.

2020-10-02 13:58 UTC, poncovka commented
Updated.

2020-10-06 13:07 UTC, jkonecny12 approved these changes
Looks good to me now. Thanks!

2020-10-07 11:11 UTC, merged