post-scripts need to be sorted
rhinstaller/anaconda pull request #2902
Opened 2020-10-06 23:26 UTC by jstodola

Because glob.glob() doesn't return a sorted list.

Resolves: rhbz#[1870493](https://bugzilla.redhat.com/show_bug.cgi?id=1870493)

Note: This change doesn't really fix bug [1870493](https://bugzilla.redhat.com/show_bug.cgi?id=1870493), in fact it makes the problem described there appear every time due to bug [1885772](https://bugzilla.redhat.com/show_bug.cgi?id=1885772) - but the problem is now reproducible reliably!
Opening this pull request as a draft to discuss if anaconda should relabel logs after copying them (and possibly allow to miss problems like bug [1885772](https://bugzilla.redhat.com/show_bug.cgi?id=1885772))

2020-10-07 07:49 UTC, VladimirSlavik commented
From the Anaconda perspective, we want to log all executions of `%post` scripts for debugging/truobleshooting purposes. These logs go to the install environment, so they need to be copied. That is done by a post script too. So there's a bit of a chicken and egg problem: To correct log contexts, they need to be in the final location, but the context fixing should be logged too.

Personally I think specifically fixing the one and only hawkey context in the "copy logs" script is what we should do - but only as a concession. It's a known problem, we know it's that, blah blah, still needs to be done somehow. In an ideal world, the file would have the right context straight away, just like all the other log files.

2020-10-07 07:51 UTC, VladimirSlavik approved these changes
Besides the meta-bikeshedding above, the change proposed here looks very good to me. Thank you for fighting nondeterminism!

2020-10-07 07:57 UTC, VladimirSlavik requested changes
Sorry, spoke too soon. If this does not fix the bug, then use `Related:` instead of `Resolves:` in the commit message, please?

2020-10-07 09:50 UTC, poncovka approved these changes
Good catch! About the labeling, I've suggested to replace the Anaconda's %post scripts with tasks (for several reasons). Then we could easily do the relabeling twice. Once before we copy the files (so the call will be logged) and once after we copy the files (so the copied files have the right label).

2020-10-08 10:50 UTC, jkonecny12 approved these changes
Looks great to me other than what was already mentioned here ;).

2020-10-11 18:52 UTC, jstodola commented
Used `Related:` in the commit message of the first commit.
Additional commit included to relabel anaconda logs after copying them to the installed system.

2020-10-12 08:36 UTC, VladimirSlavik approved these changes
I think this is as good as can be. Let's see what others think...

2020-10-12 15:43 UTC, poncovka approved these changes
It looks great! Thanks!

2020-10-14 09:16 UTC, jkonecny12 approved these changes
LGTM!

2020-10-14 09:34 UTC, VladimirSlavik commented
Blocked since bug has not been accepted yet.

2020-10-14 17:28 UTC, jstodola commented
master branch PR: #2928

2020-10-19 10:38 UTC, VladimirSlavik commented
Port to master merged.

2020-11-24 15:17 UTC, jkonecny12 commented
/test

2020-11-24 15:23 UTC, VladimirSlavik commented
Bug acked, PR no longer blocked.

2020-11-24 16:42 UTC, merged