Add selinux=0 boot parameter when SELinux is set to disabled (#1882464)
rhinstaller/anaconda pull request #2939
Opened 2020-10-21 08:56 UTC by WOnder93

We are trying to eliminate the reliance on disabling SELinux via
/etc/selinux/config in Fedora [1], since this functionality is being
deprecated upstream.

Even though only setting SELINUX=disabled in /etc/selinux/config will
still lead to a similar result as if SELinux would be disabled
completely, users might complain that Anaconda didn't actually do the
right thing, so let's make sure it is done properly by adding selinux=0
to the target system's kernel command line when the user requests
SELinux to be disabled via anaconda command line or kickstart.

[1] https://fedoraproject.org/wiki/Changes/Remove_Support_For_SELinux_Runtime_Disable

---
BTW, I didn't actually test if this code path is actually taken in the kickstart case. I just hope it uses the same code :) If my assumption is wrong, I'll be thankful for any pointers on where to make additional changes (and how to test them easily).

2020-10-22 13:54 UTC, jkonecny12 commented
Could you please rebase this PR. We had a small issue with the tests so they are not testing your code here. Everything should be fine after rebase.
Sorry for the inconvenience.

2020-10-22 13:54 UTC, jkonecny12 commented
/packit build

2020-10-22 15:46 UTC, WOnder93 commented
No problem, it's rebased now.

2020-10-26 11:08 UTC, poncovka requested changes
Otherwise, it looks good to me.

2020-10-26 11:08 UTC, poncovka commented on pyanaconda/modules/storage/bootloader/base.py
> +        if proxy.SELinux == SELinuxMode.DISABLED.value:
Please, use the `SELINUX_DISABLED` constant from from `pykickstart.constants`. The implementation of the modules is considered to be private, so a module shouldn't import code of another module.

2020-10-26 14:27 UTC, M4rtinK approved these changes
Looks good to me, thanks! :)

2020-10-26 14:47 UTC, poncovka commented
/packit build

2020-10-26 15:35 UTC, poncovka approved these changes
Looks good to me. Thank you!

2020-10-26 15:36 UTC, merged