Fix duplicated rd.shell=0 (#1907258)
rhinstaller/anaconda pull request #3078
Opened 2021-01-07 18:53 UTC by VladimirSlavik

Contributed in [rhbz#1907258](https://bugzilla.redhat.com/show_bug.cgi?id=1907258). First commit is 1:1 with the patch except for message edited for our guidelines. In the second commit I tried to pythonize the code.

Not tested yet.

2021-01-07 18:54 UTC, VladimirSlavik commented
/kickstart-test bootloader

2021-01-07 18:55 UTC, VladimirSlavik commented on pyanaconda/modules/storage/bootloader/grub2.py
> +    grub_d_file = "/etc/grub.d/10_linux"
Not sure if this is the right place to have the constant.

2021-01-08 09:29 UTC, VladimirSlavik commented
/kickstart-test bootloader

2021-01-08 10:27 UTC, poncovka commented
I don't think that this is a good idea for several reasons.

1. I wasn't able to reproduce the issue.
2. The `/etc/grub.d/10_linux` file is a script, so I don't recommend to parse the file.
3. There are more files in `/etc/grub.d/` that might add something on the cmdline.

2021-01-08 14:42 UTC, jkonecny12 commented
/kickstart-test bootloader-1

2021-01-08 15:12 UTC, VladimirSlavik commented
/kickstart-test --testtype bootloader

2021-01-08 17:15 UTC, jkonecny12 requested changes
Looks great to me otherwise. Thanks for those improvements!
Just please do the small change requested below.

2021-01-08 17:15 UTC, jkonecny12 commented on pyanaconda/modules/storage/bootloader/grub2.py
> +            grub_d_file = "%s%s" % (conf.target.system_root, self.grub_d_file)
Please use ``format`` we are trying to get rid of the ``%`` in the code.

2021-01-08 17:23 UTC, jkonecny12 commented
> I don't think that this is a good idea for several reasons.
> 
>     1. I wasn't able to reproduce the issue.

We don't have the reproducer. I guess there is a condition you need to do to have ``/etc/grub.d/10_linux`` with this parameter. Maybe asking reporter first would be a good idea here.

> 
>     2. The `/etc/grub.d/10_linux` file is a script, so I don't recommend to parse the file.

Scripts used for the configuration of the system are common. I don't see a problem with parsing that. Or do you have a specific reason why we don't want to do that?

> 
>     3. There are more files in `/etc/grub.d/` that might add something on the cmdline.

Yes, but the file mentioned above is specifically created for this purpose (I think). The same solution is used also for example for ``/etc/X11/xinit/xinitrc.d/`` for example.

2021-01-10 21:25 UTC, jstodola commented
>     2. The `/etc/grub.d/10_linux` file is a script, so I don't recommend to parse the file.
I agree with this point.
Trying to find a string **anywhere** in a ~500 lines shell script (even in a comment) simply cannot be a correct solution.

2021-01-13 13:49 UTC, jkonecny12 commented
> > ```
> > 2. The `/etc/grub.d/10_linux` file is a script, so I don't recommend to parse the file.
> > ```
> 
> I agree with this point.
> Trying to find a string **anywhere** in a ~500 lines shell script (even in a comment) simply cannot be a correct solution.

OK my bad, I did not looked on that script. If it's that long it seems really as a bad decision.

2021-01-14 16:47 UTC, VladimirSlavik commented
Blocked until we learn more, it seems.

2021-02-08 09:13 UTC, VladimirSlavik commented
It has been a month and there was no reply - neither here nor [in the bug](https://bugzilla.redhat.com/show_bug.cgi?id=1907258). Therefore I'm closing this. We can't accept patches without knowing why something is a problem, much less patches that need further work to be acceptable.

To be clear, this is not a rejection of the problem or any fix for it, just of this particular PR. The bug remains open. Do feel free to continue the discussion there, open new PRs etc. related to this problem.

2021-02-08 09:13 UTC, closed without merging