anaconda should add only s390utils-core
rhinstaller/anaconda pull request #3111
Opened 2021-01-22 08:33 UTC by sharkcz

The s390utils-core is the sufficient part of s390utils that's required for a s390x
system to be functional. Thus add only s390utils-core to the package set instead of
the complete s390utils.

Fixes: #1918642

2021-01-22 09:03 UTC, VladimirSlavik requested changes
Thanks for the change! Unit tests fail, because you need to change them too:
- https://github.com/rhinstaller/anaconda/blob/master/tests/nosetests/pyanaconda_tests/modules/storage/module_storage_test.py#L293
- https://github.com/rhinstaller/anaconda/blob/master/tests/nosetests/pyanaconda_tests/modules/storage/platform_test.py#L120

2021-01-22 09:06 UTC, VladimirSlavik commented
/packit build

2021-01-22 09:06 UTC, VladimirSlavik commented
/kickstart-test --testtype smoke

2021-01-22 09:08 UTC, sharkcz commented
ok, will fix the tests too :-)

2021-01-22 09:21 UTC, poncovka approved these changes
Looks good to me. Thanks!

2021-01-22 09:22 UTC, poncovka commented
/packit build

2021-01-22 09:43 UTC, VladimirSlavik commented
/kickstart-test --testtype smoke

2021-01-22 09:43 UTC, VladimirSlavik approved these changes
Thank you!

2021-01-22 09:53 UTC, sharkcz commented
please don't merge yet, one more fix is required :-)

2021-01-22 09:55 UTC, sharkcz commented
Now I hope I got it all right from the bz.

2021-01-22 09:58 UTC, sharkcz commented
Maybe one more thing, won't be the explicit "require" for the bootloader sufficient? Allowing to the drop the platform one?

2021-01-22 10:13 UTC, poncovka commented
/kickstart-test --testtype smoke

2021-01-22 10:13 UTC, poncovka commented
/packit build

2021-01-22 10:13 UTC, poncovka approved these changes
Still looks good to me.

2021-01-22 10:18 UTC, poncovka commented
> Maybe one more thing, won't be the explicit "require" for the bootloader sufficient? Allowing to the drop the platform one?

The bootloader can be disabled and I guess that we don't install the bootloader requirements in that case.

2021-01-22 10:21 UTC, VladimirSlavik commented
One more nitpick, for commit messages we use `Resolves: rhbz#NNNN`.

2021-01-25 12:27 UTC, poncovka commented
/test

2021-01-26 18:17 UTC, jkonecny12 commented
/test

2021-01-26 18:17 UTC, jkonecny12 commented
/packit build

2021-01-27 13:59 UTC, sharkcz commented
this can be unblocked with the last revision, IMO

2021-01-27 15:03 UTC, poncovka commented
/kickstart-test --testtype smoke

2021-01-27 15:03 UTC, poncovka commented
/test

2021-01-27 15:59 UTC, poncovka approved these changes
It looks great! Thanks!

2021-01-27 15:59 UTC, merged