Do not hard-require zram-generator-default on RHEL just yet
rhinstaller/anaconda pull request #3168
Opened 2021-02-12 17:17 UTC by M4rtinK

Drop the hard Requires on zram-generator-defaults for RHEL builds,
until it's build issues on RHEL are resolved.

2021-02-12 17:20 UTC, jkonecny12 approved these changes
Looks good to me otherwise.

2021-02-12 17:20 UTC, jkonecny12 commented on anaconda.spec.in
> +# do not require on RHEL until the package is ready
Please add this comment as FIXME.

2021-02-12 17:21 UTC, VladimirSlavik approved these changes
Looks good to me. Thank you!

2021-02-12 17:23 UTC, M4rtinK commented on anaconda.spec.in
> +# do not require on RHEL until the package is ready
Nice idea, changed! :)

2021-02-15 11:03 UTC, poncovka requested changes
The pull request needs to be rebased and it would be nice to add a number of the related bug if there is any.

2021-02-15 15:54 UTC, M4rtinK commented
> The pull request needs to be rebased and it would be nice to add a number of the related bug if there is any.

Rebased on latest f34-devel. As for a bug number, I'm afraid there is not any as far as I can tell for this issue.

2021-02-15 15:55 UTC, poncovka approved these changes
Looks good to me. Thanks!

2021-02-15 17:42 UTC, merged