Conscious language blacklist 1
rhinstaller/anaconda pull request #3202
Opened 2021-02-25 10:52 UTC by rvykydal

Note: the main reason for picking blocklist/passlist (not denylist/allowlist) was consistency with RHEL 8 installation documentation where it is already used.

2021-02-25 11:04 UTC, poncovka approved these changes
It looks good to me. Thanks!

2021-02-25 11:04 UTC, poncovka commented on pyanaconda/modules/payloads/base/utils.py
>      with open(os.path.join(sysroot, "etc/modprobe.d/anaconda-blacklist.conf"), "w") as f:
Don't we want to change the name of the file as well, or is it documented somewhere?

2021-02-25 11:05 UTC, poncovka commented
Do we want to do this in Fedora 34? Isn't it too late?

2021-02-25 11:07 UTC, poncovka commented on pyanaconda/modules/payloads/base/utils.py
>      with open(os.path.join(sysroot, "etc/modprobe.d/anaconda-blacklist.conf"), "w") as f:
Never mind. I have found https://github.com/rhinstaller/anaconda/pull/3203.

2021-02-25 11:44 UTC, VladimirSlavik approved these changes
I think this is mostly fine. The word "blocklist" makes me really sad, but if that's used elsewhere too, it's better to stay consistent.

2021-02-25 12:06 UTC, VladimirSlavik requested changes
On a further probing, I hear kernel dev wants to use "denylist". I think we should stay consistent with that.

I think it's actually an issue of RHEL docs choosing something else for installer.

2021-02-25 13:22 UTC, rvykydal commented
@VladimirSlavik thank you for digging into it, I pushed new version using 'denylist'

2021-02-25 13:33 UTC, poncovka approved these changes

2021-02-25 15:23 UTC, rvykydal commented
/kickstart-test --testtype smoke

2021-03-01 09:54 UTC, poncovka approved these changes

2021-03-02 08:16 UTC, rvykydal commented
/kickstart-test --testtype smoke

2021-03-02 11:43 UTC, VladimirSlavik approved these changes

2021-03-03 10:37 UTC, merged