Fix unknown error when entering wrong URL address
rhinstaller/anaconda pull request #3219
Opened 2021-03-04 04:54 UTC by century6

enables anaconda to recognize the error when inputting the wrong URL address in GUI instead of throwing an unknown error

2021-03-04 10:06 UTC, poncovka commented
/test

2021-03-04 10:08 UTC, VladimirSlavik commented
Hello @century6, thanks for the contribution! I haven't tried running the code yet, but it looks good to me.

Given that the change is in the branch of code handling NFS, I would prefer mentioning NFS in the commit message too. I had to re-read this thing a few times to understand it. At first sight, I got the impression that this handles URLs and is somehow stacked at the end of ifs because an error will blow past all of the ifs.

2021-03-06 12:00 UTC, century6 commented
> Hello @century6, thanks for the contribution! I haven't tried running the code yet, but it looks good to me.
> 
> Given that the change is in the branch of code handling NFS, I would prefer mentioning NFS in the commit message too. I had to re-read this thing a few times to understand it. At first sight, I got the impression that this handles URLs and is somehow stacked at the end of the if-elif chain, because an error will blow past all of the ifs.
> 
> PS: Starting contributor tests is still technically broken, but on master the old version should still work. Not sure what outcome to expect.

Sorry, it's my fault. NFS is now mentioned in the commit message.

2021-03-09 20:22 UTC, VladimirSlavik commented
I gave this a proper test, and it works, but I'm not sure it's entirely correct.

The case where the field has no colon `:` is caught by the empty `path` check, so that is redundant. What remains is the check for more than one colon, and given the preceding operations and checks, that could be simplified as `":" in path`. Then the error message should mention that only one colon is allowed, since that's the exact problem it's solving. The current message does not actually point out the specific problem found with the input.

2021-03-09 20:22 UTC, VladimirSlavik commented
/test

2021-03-11 11:24 UTC, jkonecny12 approved these changes
Looks great to me, thanks for the contribution!

2021-03-11 11:24 UTC, jkonecny12 commented
/packit build

2021-03-15 03:22 UTC, pep8speaks commented
Hello @century6! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pyanaconda/core/regexes.py`](https://github.com/rhinstaller/anaconda/blob/db44891c5160a9d6564860b3baf03a36346aa31b/pyanaconda/core/regexes.py):

> [Line 106:100](https://github.com/rhinstaller/anaconda/blob/db44891c5160a9d6564860b3baf03a36346aa31b/pyanaconda/core/regexes.py#L106): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 99 characters)

2021-03-15 08:09 UTC, century6 commented
> /test

2021-03-15 08:14 UTC, century6 commented
> I gave this a proper test, and it works, but I'm not sure it's entirely correct.
> 
> The case where the field has no colon `:` is caught by the empty `path` check, so that is redundant. What remains is the check for more than one colon, and given the preceding operations and checks, that could be simplified as `":" in path`. Then the error message should mention that only one colon is allowed, since that's the exact problem it's solving. The current message does not actually point out the specific problem found with the input.

The specific problem found with the input have been added to the message.

2021-03-15 14:09 UTC, VladimirSlavik commented
/test

2021-03-15 16:22 UTC, VladimirSlavik requested changes
Please squash the commits, we won't merge your WIP changing back and forth. Alternatively, I can do that for you - just say so!

2021-03-15 16:23 UTC, VladimirSlavik commented
kickstart-test --testtype smoke

2021-03-15 16:23 UTC, VladimirSlavik commented
/packit build

2021-03-16 06:25 UTC, century6 commented
> Please squash the commits, we won't merge your WIP changing back and forth. Alternatively, I can do that for you - just say so!

OK, I have squashed the commits.

2021-03-16 09:55 UTC, poncovka reviewed
The code looks good to me. Thank you!

2021-03-16 16:12 UTC, VladimirSlavik approved these changes
Thanks!

2021-03-16 16:12 UTC, VladimirSlavik commented
/test

2021-03-16 16:22 UTC, VladimirSlavik commented
/kickstart-test --testtype smoke

2021-03-16 16:50 UTC, merged