Assure Subscription spoke initialization in main thread
rhinstaller/anaconda pull request #3293
Opened 2021-04-15 18:45 UTC by M4rtinK

The Subscription spoke which provides the Connect to Red Hat screen
needs to wait for bot the subscription any payload setup threads
to finish before loading valid initial values and making the spoke
accessible to users.

This is implemented by starting a subscription spoke an initialization thread
that waits for the subscription and payload threads to finish. Once both
threads terminate, the subscription spoke initialization thread will update
Subscription spoke state, notify the hub initialization is done and then
terminate.

Unfortunately this means the spoke state updates, which among other
things manipulate GTK widgets, will be run from a non-main thread
(the subscription spoke initialization thread). This is a problem
as GTK is explicitly not thread safe and accessing it's objects from
non-main threads can lead to undefined behavior. Like say spoke status
not being updated correctly.

Wrapping the gtk_call_once() functions around the Subscription spoke
status update calls should serialize these calls into the main thread,
fixing the issue. Notifying the hub via the hub queue should be thread
safe & is done in other spokes from non-main threads, so wrapping that
as well should not be needed.

Resolves: rhbz#1950053

2021-04-15 19:14 UTC, poncovka requested changes
I don't think this will fix anything. These methods already use the `@async_action_wait` decorator.

2021-04-15 19:51 UTC, M4rtinK commented
> I don't think this will fix anything. These methods already use the `@async_action_wait` decorator.

Oh, right! Not to mention I I called that function incorrectly as well. :P Oh well, so much for a simple quick fix! :-)

Looking into this a bit more, I have a theory number 2:

The _initialize() method, running in the context of THREAD_SUBSCRIPTION_SPOKE_INIT calls to basically refresh the hub:

```
        # Send ready signal to main event loop
        hubQ.send_ready(self.__class__.__name__, False)

```

Yet the spoke is considered ready only once the thread is not running:
```
    @property
    def ready(self):
        """The subscription spoke is ready once its initialization thread finishes.

        We do this to avoid the Subscription spoke being set mandatory in cases
        where the current installation source is the CDN, but payload refres is still
        running and it might change to CDROM later one. We achieve this by waiting
        for tha payload refresh thread to finish in the Subscription spoke initialization
        thread.
        """
        return not threadMgr.get(THREAD_SUBSCRIPTION_SPOKE_INIT)
```
 So if hub is *quick* it might serve the refresh request when the thread is still running, meaning the spoke will still be considered not ready.

On next refresh the spoke status would be evaluated correctly as the initialization thread has since terminated.

2021-04-15 22:24 UTC, M4rtinK commented
Updated the PR with a second fix attempt.

2021-04-20 13:53 UTC, jkonecny12 reviewed
Looks good to me AFAIK. However, wasn't that deeply involved to give an ACK here.

2021-04-20 14:26 UTC, poncovka approved these changes
Looks good to me.

2021-04-20 19:14 UTC, jstodola commented
I forgot to share automated test results.
Without the patch, about 1 out of 180 installations failed due to the problem described in bug 1950053.
With the fix applied via updates.img, this problem was not seen any more during ~1100 installations executed on random systems.
(updates.img was used in both cases - with/without fix applied due to testing using anabot)

2021-04-21 10:07 UTC, jkonecny12 commented
Wow, you are testing in big numbers really. Thanks for doing that!!

2021-05-13 16:58 UTC, merged

2021-05-13 17:21 UTC, M4rtinK commented
Port to Fedora:  #3368

2021-05-13 17:35 UTC, M4rtinK commented
Port to RHEL 9: #3369