Run tests on every push to a base branch
rhinstaller/anaconda pull request #3418
Opened 2021-05-27 15:43 UTC by poncovka

We need to update the coverage of these branches in the codecov.io,
so we can compare the pull request coverage with the base coverage.

**Tested on:** https://github.com/poncovka/anaconda/runs/2686386124

2021-05-31 09:38 UTC, VladimirSlavik approved these changes
LGTM, I agree that this should not use the environment.

Thanks for fixing the coverage thing!

2021-05-31 10:14 UTC, poncovka commented
/kickstart-test --testtype smoke

2021-06-01 08:02 UTC, rvykydal approved these changes
Looks good to me.

2021-06-02 12:42 UTC, jkonecny12 approved these changes
Looks good to me. However, I don't think we should build the containers.

2021-06-02 12:42 UTC, jkonecny12 commented on .github/workflows/push-tests.yml
> +        run: make -f Makefile.am anaconda-ci-build
Do not build the container, just let it download from our quay.io repository. These will be downloaded automatically on when starting the tests. So just removing these two lines should be enough.

Or re-use this part https://github.com/rhinstaller/anaconda/blob/master/.github/workflows/tests.yml#L57 .

2021-06-02 12:43 UTC, jkonecny12 requested changes
Sorry it should have been NACK :D

2021-06-04 12:58 UTC, jkonecny12 approved these changes
After off-site discussion there is a valid reason to use this way. We are not able to detect changed files so in case there will be dependency change or Dockerfile change we won't be able to detect that.
On the other hand we are not guarded against the changes from the system. So, if some dependency will break Anaconda we would get it here but not from the repository because it's gated before the upload.

Removing NACK, this is about to choose the smaller evil in this case.

2021-06-04 12:59 UTC, merged