Don't add a prefix to the dependabot pull requests (#infra)
rhinstaller/anaconda pull request #3531
Opened 2021-07-21 11:00 UTC by poncovka

Add the (#infra) suffix once supported as it is required by the infrastructure
check. For now, add the blocked label to make sure that the pull request won't
be merged without it. We could create drafts instead of pull requests, but
that's not supported as well.

2021-07-22 14:19 UTC, VladimirSlavik requested changes
I think the infra check is what should be changed. Who says it must be a suffix?

2021-07-23 09:46 UTC, jkonecny12 commented
Honestly I'm not sure how to proceed here. One thing is that `(#infra)` could be anywhere on the other hand we are already adding bug numbers as suffix so it's a bit inconsistent to also support prefix here.

2021-07-23 12:58 UTC, VladimirSlavik commented
We don't want to merge these, so maybe it does not matter. Feel free to dismiss my nack.

2021-07-28 09:23 UTC, poncovka commented
/kickstart-test --testtype smoke

2021-07-28 09:23 UTC, jkonecny12 approved these changes

2021-07-28 09:24 UTC, VladimirSlavik approved these changes
Let's do it, it doesn't matter if we are not merging the PRs...

2021-08-02 13:36 UTC, merged