data/profile.d: Add profiles for KDE & Kinoite Spins
rhinstaller/anaconda pull request #3577
Opened 2021-08-25 17:10 UTC by travier

Both profiles are based on Workstation but use the generic Fedora Linux
branding until we make specific ones for those two spins.

Fedora Kinoite is a new Fedora variant similar to Fedora Silverblue,
introduced in Fedora 35.

See https://fedoraproject.org/wiki/Changes/Fedora_Kinoite

2021-08-28 10:22 UTC, poncovka commented
Actually, the initial setup doesn't use `VARIANT_ID` to load profile configuration files. It uses only `ID`, so I don't understand how it is broken. It should use the `fedora` configuration profile for all variants of Fedora. See: https://github.com/rhinstaller/initial-setup/blob/1ba27b4d9db7de2a46e5f208cdab65efb07c927a/initial_setup/__init__.py#L110-L112

2021-08-28 12:33 UTC, Conan-Kudo requested changes

2021-08-28 12:33 UTC, Conan-Kudo commented on data/profile.d/fedora-kinoite.conf
> +base_profile = fedora-workstation
We should be based on Fedora KDE, not Fedora Workstation.

2021-08-30 13:57 UTC, M4rtinK commented
> There was no use case for that so far, we need to figure out how to approach the issue. As a temporary workaround, we could reset the `hidden_spokes` option in the initial setup configuration file. See: https://github.com/rhinstaller/initial-setup/blob/master/data/10-initial-setup.conf

Agreed - maybe have initial setup specific variant of `hidden_spokes` so that both can be set separately?

And in general, I agree this is something Initial Setup should handle & I'm ready to help as Initial Setup maintainer.

2021-09-03 11:03 UTC, travier commented
OK, I've updated this one to mirror the workstation settings while keeping things independent until we figure out where we can share more.
As I don't think this will change much for F35, let's keep it for master only and I'll try to work on fixing the initial setup issue. Tracking issue: https://github.com/rhinstaller/initial-setup/issues/136

2021-09-06 10:04 UTC, poncovka commented
/kickstart-test --testtype smoke

2021-09-06 10:59 UTC, poncovka commented
> Agreed - maybe have initial setup specific variant of `hidden_spokes` so that both can be set separately?

That makes zero sense. I am not going to support two versions of configuration options. If we are not able to use Anaconda's profiles in Initial Setup, then Initial Setup should have its own profiles.

2021-09-06 11:19 UTC, poncovka commented
> Actually, the initial setup doesn't use `VARIANT_ID` to load profile configuration files. It uses only `ID`, so I don't understand how it is broken. It should use the `fedora` configuration profile for all variants of Fedora. See: https://github.com/rhinstaller/initial-setup/blob/1ba27b4d9db7de2a46e5f208cdab65efb07c927a/initial_setup/__init__.py#L110-L112

It means that https://github.com/rhinstaller/anaconda/pull/3577#issuecomment-907229246 is not true and you can set `hidden_spokes` in your profiles, because Initial Setup won't use them. The current support should be sufficient for your use case.

2021-09-21 14:25 UTC, travier commented
I think this one should be ready. I will try to work on the suggestion from https://github.com/rhinstaller/initial-setup/issues/136#issuecomment-920740804 in a different PR.

2021-09-21 17:24 UTC, poncovka approved these changes
Thanks!

2021-09-21 17:24 UTC, merged