Simplify release notes (#infra)
rhinstaller/anaconda pull request #3776
Opened 2022-01-10 16:13 UTC by VladimirSlavik

Version no longer duplicated in title and text.

2022-01-11 12:48 UTC, jkonecny12 requested changes
Please verify that the new line at the end is not a problem first. Otherwise looks great.

2022-01-11 12:48 UTC, jkonecny12 commented on .github/workflows/tag-release.yml
> -              | tee -a release.txt
I think that we also want a trim to remove `\n` on the last line.

2022-01-11 14:40 UTC, jkonecny12 approved these changes
LGTM!

2022-01-11 14:40 UTC, jkonecny12 commented on .github/workflows/tag-release.yml
> +          truncate -s -1 release.txt
I'm thinking about more robust solution in case there won't be a ending newline but -- naah that shouldn't happen. :D

2022-01-11 14:53 UTC, VladimirSlavik commented on .github/workflows/tag-release.yml
> +          truncate -s -1 release.txt
There was that tempting perl one-liner somewhere on stack overflow...

2022-01-11 14:53 UTC, VladimirSlavik commented
/kickstart-test --testtype smoke

2022-01-18 12:48 UTC, VladimirSlavik commented
/kickstart-test --testtype smoke

2022-01-18 13:51 UTC, merged