Enable the Koji repository in the RPM tests
rhinstaller/anaconda pull request #3823
Opened 2022-02-03 17:25 UTC by poncovka

Use the latest updates to fix our issues with the RPM tests.

2022-02-03 17:35 UTC, poncovka commented
I have no idea what is actually broken, but enabling the Koji repository seems to resolve the issues with RPM tests.

2022-02-03 17:37 UTC, poncovka commented
/kickstart-test --testtype smoke

2022-02-04 12:10 UTC, jkonecny12 requested changes
This solution is great for test that there is already a fix in koji but I would like to avoid having Koji as our repository. It could break any second and there is no testing of that.

2022-02-04 12:10 UTC, jkonecny12 commented on Makefile.am
> +CONTAINER_BUILD_ARGS ?= --no-cache --pull-always
Already part of https://github.com/rhinstaller/anaconda/pull/3812.

2022-02-04 12:40 UTC, jkonecny12 commented
Seems that this issue is now resolved even without this PR. Tested locally and I'll also run the container refresh to be sure.

2022-02-04 13:12 UTC, jkonecny12 commented
Tested, we have working infra again - we can close this now.

2022-02-04 14:25 UTC, poncovka commented
Well, I am going to fix the next breakage the same way. We can discuss this solution at Monday's meeting.

2022-02-04 14:25 UTC, closed without merging