Restore contexts also in /var/lib
rhinstaller/anaconda pull request #3841
Opened 2022-02-09 15:11 UTC by VladimirSlavik

New RPM touches that location too.

Resolves: [rhbz#2052038](https://bugzilla.redhat.com/show_bug.cgi?id=2052038)

2022-02-09 15:23 UTC, VladimirSlavik commented
CC @t184256 maybe of interest to you?

2022-02-09 15:45 UTC, VladimirSlavik commented
/kickstart-test --testtype smoke

2022-02-10 13:52 UTC, M4rtinK requested changes
Looks good code wise but commit message says /var/lib while code has /usr/lib - I think that should be fixed. :)

Also I also think this should go to F36 as well as the need for this fix is most likely triggered by the following F36 change: https://fedoraproject.org/wiki/Changes/RelocateRPMToUsr

(Also I think it might be good to link to the change from the commit message as well.)

2022-02-14 08:02 UTC, rvykydal approved these changes
Looks good to me, thank you.

2022-02-14 11:37 UTC, jkonecny12 approved these changes
Looks good to me.

2022-02-14 11:39 UTC, M4rtinK approved these changes
Looks good to me, thanks! :)

2022-02-14 11:40 UTC, VladimirSlavik commented
/kickstart-test --testtype smoke

2022-02-14 13:20 UTC, merged