Improve Simple Content Access UX (RHEL 8)
rhinstaller/anaconda pull request #3867
Opened 2022-02-15 03:10 UTC by M4rtinK

Show a proper status message instead of a confusing (even if correct) message about no subscription being attached if install time registration is done in Simple Content Access mode.

This is achieved by parsing the data returned by the register methods of the RHSM DBus, exposing this via a DBus property of the Subscription module, which is then used by the GUI to display the appropriate string.

2022-02-15 03:10 UTC, pep8speaks commented
Hello @M4rtinK! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pyanaconda/modules/subscription/runtime.py`](https://github.com/rhinstaller/anaconda/blob/41843c1e24dd6bdf80262d047bf7e8bde55e820f/pyanaconda/modules/subscription/runtime.py):

> [Line 297:100](https://github.com/rhinstaller/anaconda/blob/41843c1e24dd6bdf80262d047bf7e8bde55e820f/pyanaconda/modules/subscription/runtime.py#L297): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 99 characters)





* In the file [`pyanaconda/modules/subscription/utils.py`](https://github.com/rhinstaller/anaconda/blob/41843c1e24dd6bdf80262d047bf7e8bde55e820f/pyanaconda/modules/subscription/utils.py):

> [Line 26:1](https://github.com/rhinstaller/anaconda/blob/41843c1e24dd6bdf80262d047bf7e8bde55e820f/pyanaconda/modules/subscription/utils.py#L26): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2022-02-15 03:13 UTC, M4rtinK commented
We can't merge this until subscription-manager 1.28.26 has been released an is available in the compose. So setting the blocked label.

2022-02-15 13:42 UTC, poncovka requested changes
Pylint found some isssues.

2022-02-17 02:29 UTC, M4rtinK commented
> Pylint found some issues.

Pylint issues have been fixed up. :)

2022-02-21 03:26 UTC, M4rtinK commented
/kickstart-test --testtype smoke

2022-02-21 09:32 UTC, jstodola commented
https://bugzilla.redhat.com/show_bug.cgi?id=2049101 with subscription-manager-1.28.28-1.el8 is in ON_QA, so this PR is not blocked by subscription-manager any more.

2022-02-21 11:38 UTC, M4rtinK commented
> https://bugzilla.redhat.com/show_bug.cgi?id=2049101 with subscription-manager-1.28.28-1.el8 is in ON_QA, so this PR is not blocked by subscription-manager any more.

Yeah, dropping the blocked label. :) Last kickstart test run still had some issues picking up the new subscription-manager package, so re-running that.

2022-02-21 16:34 UTC, jkonecny12 approved these changes
Looks good to me except this small nitpick.

2022-02-22 08:05 UTC, poncovka approved these changes
Please, fix the issue above. Otherwise, it looks good to me.

2022-02-22 14:27 UTC, M4rtinK commented
> Please, fix the issue above. Otherwise, it looks good to me.

Issue has been fixed.

2022-02-22 14:29 UTC, M4rtinK commented
/kickstart-test --testtype smoke

2022-02-22 16:14 UTC, poncovka approved these changes
Thanks!

2022-02-23 15:54 UTC, merged