Fix icon names to use -symbolic
rhinstaller/anaconda pull request #3900
Opened 2022-02-25 14:58 UTC by VladimirSlavik

The non-symbolic icons are no longer available.

CC @jkonecny12

2022-02-25 14:58 UTC, pep8speaks commented
Hello @VladimirSlavik! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pyanaconda/ui/gui/helpers.py`](https://github.com/rhinstaller/anaconda/blob/14a9acbcf3f4bf380998a988d01b781faf1aab58/pyanaconda/ui/gui/helpers.py):

> [Line 158:21](https://github.com/rhinstaller/anaconda/blob/14a9acbcf3f4bf380998a988d01b781faf1aab58/pyanaconda/ui/gui/helpers.py#L158): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

2022-02-25 15:15 UTC, jkonecny12 requested changes
I'm trying to also adjust the size of the icons because they are really ugly on some places but that can be done after this is resolved. Thanks.

However, rebase this to f36-devel. Based on container builds it's broken there too.

2022-02-25 15:23 UTC, VladimirSlavik commented
The point of this was to keep somewhere the list of changes - I think I found more places with icons than the tests know.

2022-02-28 09:15 UTC, VladimirSlavik commented
Yes! Thank you, that means I can use your PR...

2022-02-28 09:15 UTC, closed without merging