webui: Add inline alert to the Storage screen
rhinstaller/anaconda pull request #4102
Opened 2022-05-12 17:36 UTC by M4rtinK

2022-05-13 08:57 UTC, VladimirSlavik approved these changes
Looks good to me. Thank you!

2022-05-13 10:08 UTC, M4rtinK commented
![no_alert](https://user-images.githubusercontent.com/829558/168261963-2d9fabb5-693d-4392-b596-405e13ffa6f1.png)
So this is how it used to look without the alert.
![alert](https://user-images.githubusercontent.com/829558/168262037-687b449e-93dc-4d51-acf8-a68bb9fc4891.png)
This is how it looks now.

2022-05-13 11:45 UTC, M4rtinK commented
/kickstart-test --testtype smoke

2022-05-19 09:46 UTC, M4rtinK commented
/kickstart-test --testtype smoke

2022-05-19 09:46 UTC, poncovka requested changes

2022-05-19 09:46 UTC, poncovka commented on ui/webui/src/components/storage/InstallationDestination.jsx
> +              title={_("Selected disks will be erased at at install")}
at at

2022-05-24 19:21 UTC, M4rtinK commented
After rebasing on latest master branch, it looks like there is a subtle glitch where the icon is not aligned with the text:
![TestStorage-testLocalStandardDisks-storage-step-basic-pixels](https://user-images.githubusercontent.com/829558/170115442-5c24c6b3-39d5-4922-83b4-45aff9ceec59.png)

As the code in the PR worked before yet is still the same, this is likely a non-fatal side effect of one of the recent PRs and can be fixed later.

2022-05-24 19:54 UTC, merged

2022-05-25 09:03 UTC, poncovka commented on ui/webui/src/components/storage/InstallationDestination.jsx
> +              title={_("Selected disks will be erased at at install")}
Well, it was merged with the typo.