Web UI: Fix strings
rhinstaller/anaconda pull request #4122
Opened 2022-05-19 14:46 UTC by poncovka

* Fix the capital letter in `Installer`.
* Replace the `Storage configuration` title.
* Use only a plural form for the selected disks.

2022-05-19 15:34 UTC, VladimirSlavik requested changes
Lower i is fine, the plural form is an English-only change.

2022-05-19 15:34 UTC, VladimirSlavik commented on ui/webui/src/components/storage/InstallationDestination.jsx
> +                        "$0 (of $1) disks selected",
This is incorrect in most languages. See https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html after "The following rules are known at this point.".

2022-05-23 08:14 UTC, VladimirSlavik commented on ui/webui/src/components/storage/InstallationDestination.jsx
> +                        "$0 (of $1) disks selected",
FWIW, this is a design problem, not a PR problem, really.

2022-05-23 10:31 UTC, poncovka commented
Updated.

2022-05-23 10:52 UTC, VladimirSlavik approved these changes
Thank you, LGTM.

You will have to change the names also in the tests, but that's expected.

2022-05-23 20:15 UTC, jkonecny12 approved these changes
Looks good to me.

2022-05-24 10:02 UTC, poncovka commented
/kickstart-test --testtype smoke

2022-05-24 11:26 UTC, poncovka commented
/kickstart-test --testtype smoke

2022-05-24 12:18 UTC, merged

2022-06-03 13:41 UTC, lclay2 commented
@poncovka , I replied to your question on the slide deck.