Add missing period when concatenating password error strings (#2075419)
rhinstaller/anaconda pull request #4128
Opened 2022-05-23 10:35 UTC by jkonecny12

Without this change we have in the bottom line messages like:

"The password fails the dictionary check - it is too simplistic/systematic You will have to press Done twice to confirm it."

The missing period between sentences could be a big issue for understanding the sentence in languages like Chinese.

The fix here is not great one because we are not owners of both strings.

The first sentence comes from the libreport library the second one from us. Here we have two possible solutions. One would be to add translatable concatenation (what I'm doing here) and second is to add the period into the `...press Done twice...` message. I don't like to duplicate the second part so I rather add the new "{}. {}" for translations.

*Resolves: rhbz#2075419*

2022-05-23 10:35 UTC, pep8speaks commented
Hello @jkonecny12! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pyanaconda/core/constants.py`](https://github.com/rhinstaller/anaconda/blob/3fbf2b3de6ea5914fb76eee6e6d33e5173587231/pyanaconda/core/constants.py):

> [Line 239:64](https://github.com/rhinstaller/anaconda/blob/3fbf2b3de6ea5914fb76eee6e6d33e5173587231/pyanaconda/core/constants.py#L239): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2022-05-23 10:36 UTC, jkonecny12 commented
/kickstart-test --testtype smoke

2022-05-23 10:42 UTC, jkonecny12 commented
Before:
![Screenshot_jk_test_2022-05-23_12:41:09](https://user-images.githubusercontent.com/1643889/169802283-34c2beaf-d4b3-41ec-a125-dca7ab3bfa4e.png)

After:
![Screenshot_jk_test2_2022-05-23_12:40:58](https://user-images.githubusercontent.com/1643889/169802245-16269ef7-06ba-4360-bf4a-7442d5ee17d8.png)

2022-05-23 10:42 UTC, jkonecny12 commented
/kickstart-test --testtype smoke

2022-05-23 12:48 UTC, VladimirSlavik requested changes
Sorry, this won't work, or at least not as you perhaps intend it to work. If you want to use context, then the below is how you would do it.

The reason it "works" now is that the code defaults to passing through the string if not found, but would be never translated.

2022-05-23 13:12 UTC, VladimirSlavik commented
Aside from making it work, I think this is a good enough solution.

I also missed the obvious - perhaps a context is not needed after all. Context is useful when you have more "variants" of the same string literal, which is not the case here. A translator comment might be better instead. Then you have only one string to handle.

Having the string directly in the `show_warning_message` call might be better, it will be automatically detected as a format string:

```
self.show_warning_message(
  # TRANSLATORS: Concatenation of two error messages, first is lacking period (.) at end of sentence.
  _("{}. {}").format(
    error_message,
    _(constants.PASSWORD_DONE_TWICE)
  )
)
```

2022-05-23 14:06 UTC, jkonecny12 commented
Adding version with the translator comment. However, still waiting for Ludek confirmation.

2022-05-23 14:57 UTC, jkonecny12 commented
/kickstart-test --testtype smoke

2022-05-23 15:11 UTC, VladimirSlavik approved these changes
Looks good to me. Thank you!

2022-06-08 08:55 UTC, rvykydal approved these changes

2022-06-08 08:57 UTC, merged