Speed up disk spoke
rhinstaller/anaconda pull request #4192
Opened 2022-06-10 19:37 UTC by mikhailnov

Fix Anaconda freeze for 6-8 sec when leaving the storage spoke
by calculating required space not by calculating size of each file inside /,
but by taking a ready to use size of the mounted squashfs image.

Idea and implementation by Oleg Solovev @Gel0bmstu 

P.S. It is a port of the patch for the rhel-9 branch (https://abf.io/import/anaconda/blob/573b765478/0030-ROSA-fix-aloithm-for-determining-required-disk-space.patch), I am not sure that I've ported it correctly, especially in the place of `return get_dir_size`, please check...

2022-06-10 19:37 UTC, pep8speaks commented
Hello @mikhailnov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pyanaconda/core/storage.py`](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/core/storage.py):

> [Line 37:11](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/core/storage.py#L37): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 38:11](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/core/storage.py#L38): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 39:11](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/core/storage.py#L39): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 330:1](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/core/storage.py#L330): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 330:43](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/core/storage.py#L330): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 335:1](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/core/storage.py#L335): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 338:1](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/core/storage.py#L338): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 341:1](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/core/storage.py#L341): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`pyanaconda/modules/payloads/source/live_os/live_os.py`](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/modules/payloads/source/live_os/live_os.py):

> [Line 33:1](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/modules/payloads/source/live_os/live_os.py#L33): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 74:1](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/modules/payloads/source/live_os/live_os.py#L74): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 74:1](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/modules/payloads/source/live_os/live_os.py#L74): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 75:1](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/modules/payloads/source/live_os/live_os.py#L75): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 76:1](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/modules/payloads/source/live_os/live_os.py#L76): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 77:1](https://github.com/rhinstaller/anaconda/blob/3e42ddf9a10300253daab5174eae6588ee613a32/pyanaconda/modules/payloads/source/live_os/live_os.py#L77): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs

2022-06-14 18:05 UTC, mikhailnov commented
Hm, I think you are right, I have to minify the patch. Its initial description was confusing. Can you please comment, is return of disk_usage(DRACUT_ISODIR) correct?

2022-06-15 08:29 UTC, poncovka requested changes
I am going to block this change for now. It took a lot of effort to make this code work right, so I don't want to mess with it unless it is absolutely necessary. If  `get_dir_size("/")` takes a lot of time, it shouldn't be calculated in the property, but in the `SetUpLiveOSSourceTask` class. We do something similar in `SetUpLocalImageSourceTask`. Let's start from there and see if any further changes are still needed.

2022-08-05 08:13 UTC, poncovka commented
> If `get_dir_size("/")` takes a lot of time, it shouldn't be calculated in the property, but in the `SetUpLiveOSSourceTask` class. We do something similar in `SetUpLocalImageSourceTask`. Let's start from there and see if any further changes are still needed.

This will be fixed with https://github.com/rhinstaller/anaconda/pull/4247/.

2022-08-05 09:46 UTC, mikhailnov commented
Great, thanks!

2022-08-05 09:46 UTC, closed without merging