Fix product config product_name for Rocky Linux (#2096046)
rhinstaller/anaconda pull request #4194
Opened 2022-06-12 08:01 UTC by nazunalika

Currently, the Rocky Linux rocky.conf file for anaconda has inconsistent naming and does not match our previous versions. This caused us some issues during testing including our own automated pipeline. This PR is to try to bring it into consistency to state "Rocky Linux" instead of just "Rocky" in any anaconda installer references for future Enterprise Linux 9 versions.

The following bug report has also been opened for this: https://bugzilla.redhat.com/show_bug.cgi?id=2096046

Please let me know if the commits or changed files need to be addressed! Also let me know if there should be changes done in the master/main branch to also reflect this or any recommendations you may have. Thank you so much!

2022-06-13 15:54 UTC, VladimirSlavik requested changes
Thanks! There are a few things missing before it's fully acceptable:
- You will have to change the unit test too. It's just the name. See the details link under "Some checks were not successful" below.
- As far as I can tell, the part `Resolves: rhbz#` is mandatory for commit messages, regardless of having the bug number in first line. (Feel free to prove me wrong!)

If you need help, feel free to ask.

2022-06-13 16:11 UTC, nazunalika commented
Thank you! I apologize for missing the "resolves" part. Either way, I will get those fixed!

I did a push just now, so hopefully that resolves both...

2022-06-14 10:36 UTC, VladimirSlavik approved these changes
Looks good to me. Thank you!

2022-06-14 10:36 UTC, VladimirSlavik commented
/kickstart-test --testtype smoke

2022-06-17 09:55 UTC, jkonecny12 commented
All the ACKs are now on the bug. This change could be mark for release.

2022-07-13 10:04 UTC, jkonecny12 approved these changes

2022-07-14 18:52 UTC, merged