webui: do not expose context menu in local Web UI
rhinstaller/anaconda pull request #4418
Opened 2022-11-04 13:50 UTC by rvykydal

The IP address used to identify local installation is set in cockpit-desktop script.

2022-11-04 13:51 UTC, rvykydal commented
I am using detection of local installation in installer app, alternative solutions could be:
- Turning the context menu off (conext-menu signal) in webview of CockpitClientWindow in cockpit-client.  Potentially depending on Anaconda specific option/profile set in cockpit-client via cockpit-desktop.
- Detection of local installation based on inst.webui.remote boot option. But currently the option is set on the boot.iso images we produce, and both remote cockpit-ws and local cockpit-ws with cockpit-client is run with the option which seems somehow unclear.

2022-11-07 10:52 UTC, M4rtinK commented
> * Detection of local installation based on inst.webui.remote boot option. But currently the option is set on the boot.iso images we produce, and both remote cockpit-ws and local cockpit-ws with cockpit-client is run with the option which seems somehow unclear.

Yeah, I agree this would not be a good indicator, especially going forward - even if we keep this option, custom installer image builds still could have it for example even if the actual user still connects locally. Also I think its likely we will drop the option and enable remote access by default once some authentication options (like type in locally displayed auto-generated password) are available.

2022-11-07 10:57 UTC, M4rtinK approved these changes
Looks good to me, at least for now & for a solution not needing changes in the WebKit wrapper script. :)

2022-11-07 10:57 UTC, M4rtinK commented on ui/webui/src/helpers/conf.js
> +    return window.origin.startsWith(`http://${LOCAL_IP_ADDRESS}`);
I wonder if this could be https as well at some point when running locally? I guess we can fix that when/if it happens, though.

2022-11-07 11:10 UTC, M4rtinK requested changes
So actually, looking into this more closely - this would fully disable the the context menu which I'm not sure we want to do, as we would loose access to the debug console when running locally.

I guess we could conditionalize it on inst.debug or something like that, but I wonder if it would not just make it hard to use for the people actually wanting to access it.

2023-02-08 02:37 UTC, closed without merging