Make text in custom_storage_helper more accurate rebase to RHEL-9
rhinstaller/anaconda pull request #4439
Opened 2022-11-23 12:56 UTC by OndrejZobal

The window for selecting the disks to be used for a mount point doesn't say clearly that only one of the selected devices will be used. Added an additional label that explains this behaviour.

Resolves: rhbz#[2133046](https://bugzilla.redhat.com/show_bug.cgi?id=2133046)

2022-11-23 14:58 UTC, poncovka approved these changes
Thanks!

2022-11-23 14:58 UTC, poncovka commented
/kickstart-test --testtype smoke

2022-12-07 10:15 UTC, VladimirSlavik approved these changes
Thanks!

2023-01-10 16:21 UTC, jstodola requested changes
There is an incorrect bug number in the PR/commit message. It should be [2133046](https://bugzilla.redhat.com/show_bug.cgi?id=2133046)

2023-01-10 21:47 UTC, jkonecny12 commented
Thanks for pointing that out @jstodola.
@OndrejZobal could you fix that please?

2023-01-10 21:47 UTC, jkonecny12 commented
Removing ready to merge label until this is solved.

2023-01-18 12:01 UTC, OndrejZobal commented
/kickstart-test --testtype smoke

2023-02-02 15:22 UTC, merged