WebUI: Hide progress stepper after finishing
rhinstaller/anaconda pull request #4605
Opened 2023-03-08 14:17 UTC by OndrejZobal

Hide progress stepper after installation finishes and show text instead.

The word Anaconda should be replaced with a real product name.

2023-03-09 17:09 UTC, VladimirSlavik approved these changes
Looks good to me. Thank you!

2023-03-13 12:27 UTC, M4rtinK approved these changes
Looks good to me as well, thanks! :)

2023-03-13 14:25 UTC, OndrejZobal commented
![obrazek](https://user-images.githubusercontent.com/40278421/224730235-3705d404-c916-4159-9b45-edcbf4ef07c8.png)

Current iteration

2023-03-15 08:09 UTC, OndrejZobal commented
/kickstart-test --testtype smoke

2023-03-15 20:46 UTC, lclay2 requested changes
Hi, if based on the latest screenshot, it appears that the final microcopy has not been put in yet (see issue), but the spacing changes look good. If I'm missing the updates because I need to look at an image file to review the changes, please let me know which one. Thanks :) 
This is the final copy that was provided: 
"**Successfully installed**
To begin using Fedora Linux ## (Workstation Edition), reboot your system"

2023-04-27 10:16 UTC, rvykydal commented
This has been merged in https://github.com/rhinstaller/anaconda/pull/4709

2023-04-27 10:16 UTC, closed without merging