WebUI: document pixel-test fetch command
rhinstaller/anaconda pull request #4756
Opened 2023-05-11 08:16 UTC by jelly

For example:

```
GITHUB_BASE=rhinstaller/anaconda ./test/common/pixel-tests fetch "https://cockpit-logs.us-east-1.linodeobjects.com/pull-4728-20230505-082156-923abdb2-fedora-rawhide-boot/log.html"
```

Fetches the changed pixels for you and you only need to call `make update-reference-images` afterwards

2023-05-11 08:17 UTC, jelly commented
/kickstart-test --waive webui only

2023-05-15 11:49 UTC, VladimirSlavik approved these changes
Thank you!

2023-05-15 14:29 UTC, jkonecny12 commented
Hi @jelly this is already documented a few lines below. Could you please avoid duplication of this documentation? I'm fine with removing the old one if you think that is better.

2023-05-15 14:30 UTC, jkonecny12 requested changes
Duplication of documentation should be avoided first.

2023-05-15 16:12 UTC, VladimirSlavik commented
The example below does not use `GITHUB_BASE` - what's the difference?

2023-05-15 17:32 UTC, jkonecny12 commented
I think it's safer to have that specified, maybe even required. I have a feeling I wrote that without having place to test it.

2023-05-17 08:25 UTC, jelly commented
@jkonecny12 GITHUB_BASE is required as otherwise you would push pixel tests to cockpit-project, I've made it explicit now.

2023-05-17 12:36 UTC, jkonecny12 approved these changes
Looks great to me now. Thanks for the improvement!

2023-05-17 13:26 UTC, VladimirSlavik approved these changes
Thanks!

I'd say looks good to me, but apparently I'm getting blind :D

2023-05-30 11:26 UTC, jkonecny12 commented
/kickstart-test --waive docs only

2023-05-30 11:27 UTC, merged