webui: adding PRETTY_NAME to use in title instead of anaconda generic title
rhinstaller/anaconda pull request #4830
Opened 2023-06-12 19:35 UTC by acruzgon

According to UX, "_Anaconda_" should never show to people to avoid confusion. This PR is to start using `PRETTY_NAME` instead of the generic Anaconda title.

Before:
![image](https://github.com/rhinstaller/anaconda/assets/88343229/38f5b25a-04d6-491a-81d2-988e4973c32a)

After:
![image](https://github.com/rhinstaller/anaconda/assets/88343229/85f8638e-c648-4742-841b-1dc9a7ce11f9)

2023-06-13 10:05 UTC, KKoukiou requested changes
Some small fixups needed. Also tests :)

2023-06-13 10:05 UTC, KKoukiou commented on ui/webui/src/components/localization/InstallationLanguage.jsx
> +        readPrettyName().then(
Can be nicely written as one linter. readPrettyName().then(setIsPrettyName);

2023-06-13 13:44 UTC, garrett requested changes
Thanks for making this change!

There's a minor difference what what I intended: I was thinking of having the full distribution name + version at the top and the welcome to message only have the distribution name (without version).

2023-06-13 15:44 UTC, VladimirSlavik reviewed
1) I'm not sure this is the right place where the data should come from. Take a look at `pyanaconda/product.py` - that loads `/.buildstamp` and environment variables. This should work similarly, in fact we already get `isFinal` from buildstamp in `betanag.js`.

2) I don't think `conf.js` is the right place for the helper. Maybe some reorganization is in order, so that the betanag stuff and anything else reading buildstamp are together?

2023-06-16 02:15 UTC, acruzgon commented on ui/webui/src/components/app.jsx
> +        readPrettyName().then(
as talked, this is done by running `npm run eslint:fix`

2023-06-16 03:05 UTC, acruzgon commented
@garrett it would like this:
![image](https://github.com/rhinstaller/anaconda/assets/88343229/94f06edc-f5c6-428b-bde4-7b2c575f35f3)
is that okay?

2023-06-16 14:06 UTC, KKoukiou requested changes

2023-06-16 14:06 UTC, KKoukiou commented on ui/webui/src/components/app.jsx
> +            setIsPrettyName,
Please remove comma, this is just not failing because - JS - but it does not belong there.

2023-06-16 14:06 UTC, KKoukiou commented on ui/webui/src/components/localization/InstallationLanguage.jsx
> +    const [distributionName, setIsDistributionName] = useState("");
the setter name needs fix. s/setIsDistributionName/setDistributionName
(remove the Is)

2023-06-16 14:06 UTC, KKoukiou commented on ui/webui/src/components/localization/InstallationLanguage.jsx
> +    const [distributionName, setIsDistributionName] = useState("");
It's common to use 'Is' as part of the state var if it's boolean. For example:
const [isValid, setIsValid] = useState(true);

2023-06-19 06:32 UTC, KKoukiou reviewed
Please don't include merge commits and/or empty commits in your PRs.

2023-06-19 08:04 UTC, KKoukiou commented
/kickstart-test --waive webui only

2023-06-19 09:52 UTC, KKoukiou commented
/kickstart-test --waive webui only

2023-06-19 09:54 UTC, merged