setting timeout for download cockpit rpms
rhinstaller/anaconda pull request #4836
Opened 2023-06-14 14:52 UTC by acruzgon

2023-06-14 14:55 UTC, KKoukiou requested changes
As mentioned on slack this needs commit message imporovements:
something like:

webui: increase timeout for downloading anaconda-webui dependencies

The current timeout is very tight for contributors with slow connections.

2023-06-14 15:36 UTC, M4rtinK commented
BTW, we actually have some guidelines for commit messages: 
https://anaconda-installer.readthedocs.io/en/latest/contributing.html#guidelines-for-commits

2023-06-14 15:40 UTC, KKoukiou reviewed
You need to squash the two commits. In anaconda we don't squash on merge, so commits should be already squashed when sending.

2023-06-15 08:04 UTC, KKoukiou approved these changes

2023-06-15 08:04 UTC, KKoukiou commented
/kickstart-test --waive webui only

2023-06-15 12:51 UTC, merged