infra: Enable @storage/udisks-daily Copr repo for CI images
rhinstaller/anaconda pull request #4909
Opened 2023-07-12 13:39 UTC by vojtechtrefny

The blivet-daily Copr repository contains latest release of libblockdev which cannot be installed together with udisks2 (which Anaconda depends on) so the result is that incompatible versions of blivet, libblockdev and udisks2 are installed together in the image. Adding the repository that also includes daily builds of udisks2 should fix this.

2023-07-12 13:53 UTC, jkonecny12 approved these changes
Looks good to me. Thanks for the improvement.

2023-07-12 13:55 UTC, jkonecny12 requested changes
OK, you need to change also https://github.com/rhinstaller/anaconda/blob/master/dockerfile/anaconda-rpm/Dockerfile#L47

2023-07-13 09:05 UTC, vojtechtrefny commented
> OK, you need to change also https://github.com/rhinstaller/anaconda/blob/master/dockerfile/anaconda-rpm/Dockerfile#L47

Fixed.

2023-07-14 15:56 UTC, M4rtinK approved these changes
Looks good to me. :)

2023-07-19 09:35 UTC, VladimirSlavik commented
/kickstart-test --waive infra only

2023-07-19 09:37 UTC, VladimirSlavik approved these changes
Thank you!

I wonder if packit and tmt need this too, but I think not. They don't certainly have the other coprs we use.

2023-07-21 15:22 UTC, merged