webui: start using payload from the bots repository
rhinstaller/anaconda pull request #4986
Opened 2023-07-31 10:10 UTC by KKoukiou

2023-07-31 15:36 UTC, martinpitt commented on ui/webui/test/machine_install.py
> +        self.http_server.communicate()
This is the problem with the forever-hanging test. communicate() waits until the spawned process exits, which will never happen until you kill it. Instead, use `m.wait_for_cockpit_running('127.0.0.1', http_port)` until it is up, let it run in the background, and set up a cleanup handler which does `.terminate()` and `.wait()`.

2023-08-01 10:10 UTC, martinpitt commented on ui/webui/test/machine_install.py
> +    def _wait_http_server_running(self, port):
What is wrong with the existing `wait_for_cockpit_running('127.0.0.1', http_port)` [code](https://github.com/cockpit-project/bots/blob/000d0e34b42a978ad13b6ab55219fbff8296eeff/machine/machine_core/machine.py#L320) ? You can't access that API from anaconda, due to the different Machine class?

2023-08-01 10:15 UTC, martinpitt requested changes
Nice, thanks!

2023-08-01 11:18 UTC, martinpitt commented on ui/webui/test/machine_install.py
> +    def _wait_http_server_running(self, port):
Yeah, the name is confusing, it should really be called `wait_for_http_port`..

2023-08-01 11:46 UTC, KKoukiou commented on ui/webui/test/machine_install.py
> +        self.http_payload_server = subprocess.Popen(["python3", "-m", "http.server", "-d", payload_cached_dir, str(http_payload_port)])
Fixed.

2023-08-01 11:51 UTC, martinpitt commented on ui/webui/test/machine_install.py
> +    def _wait_http_server_running(self, port):
Argh, my bad :see_no_evil:

2023-08-01 11:52 UTC, martinpitt approved these changes
Cheers!

2023-08-01 12:55 UTC, KKoukiou commented
/kickstart-test --waive webui only

2023-08-01 12:56 UTC, merged