infra: remove -1 suffix from the upstream release tag name
rhinstaller/anaconda pull request #5609
Opened 2024-04-23 14:08 UTC by KKoukiou

Resolves: INSTALLER-3953

2024-04-23 14:19 UTC, jkonecny12 requested changes
I like this but please resolve the issues below first.

2024-04-23 14:19 UTC, jkonecny12 commented on .github/workflows/release-automatically.yml
> -          # 0 -> anaconda-38.6-1
Please re-render the infra files. This is not consistent with the template.

2024-04-23 14:19 UTC, jkonecny12 commented on scripts/makebumpver
> +                                           newVersion, self.new_release))
This is not correct. You are removing `release` here, however, you need that in changelog. You need to add something like:
```
new_release = self.new_release or "-1"
```

2024-04-24 10:52 UTC, KKoukiou commented
@jkonecny12 or anyone else (CC @M4rtinK @rvykydal) - can someone explain me what's the difference between the args.release and args.new_release in the scripts/makebumpver?

I asked also in the chat, but still dont have understanding.

2024-04-24 15:53 UTC, jkonecny12 commented
I answered you in the chat. TL;DR it's probably not used a long time by anyone.

2024-04-26 07:28 UTC, jkonecny12 requested changes
I still think that this will break the `%changelog` section.

2024-04-26 09:27 UTC, jkonecny12 approved these changes
Looks good to me now. Thanks!

2024-04-29 12:40 UTC, KKoukiou commented
/kickstart-test --waive infra only

2024-04-29 13:00 UTC, merged