webui: Dont run browser as root
rhinstaller/anaconda pull request #5689
Opened 2024-06-04 09:04 UTC by adamkankovsky

Inspirated by: https://github.com/rhinstaller/anaconda/pull/5058

2024-06-05 07:16 UTC, adamkankovsky commented
/build-image --live

2024-08-15 11:21 UTC, KKoukiou commented
/build-image --live

2024-08-15 15:12 UTC, KKoukiou commented
/build-image --live

2024-08-16 06:56 UTC, KKoukiou commented
/build-image --live

2024-08-19 08:10 UTC, KKoukiou commented
/build-image

2024-09-05 09:36 UTC, KKoukiou commented
/build-image --live

2024-10-09 09:00 UTC, KKoukiou commented
/kickstart-tests --testtype smoke

2024-10-09 09:02 UTC, KKoukiou requested changes

2024-10-09 09:02 UTC, KKoukiou commented on dockerfile/anaconda-iso-creator/pkexec-command.patch
> +diff --git a/share/templates.d/99-generic/runtime-cleanup.tmpl b/share/templates.d/99-generic/runtime-cleanup.tmpl
This needs to be fixed upstream Please. 

Create a PR and add a link here with FIXME to remove: https://github.com/weldr/lorax/blob/master/share/templates.d/99-generic/runtime-cleanup.tmpl

2024-10-23 07:58 UTC, jkonecny12 commented
This PR conflicts with https://github.com/rhinstaller/anaconda/pull/5946

2024-10-23 07:59 UTC, jkonecny12 commented
But I would like to see both merged soon.

2024-10-25 16:14 UTC, KKoukiou commented
/kickstart-tests --waive ran already before rebase

2024-10-25 16:14 UTC, merged