Remove deprecated warnings for inst prefix
rhinstaller/anaconda pull request #5723
Opened 2024-06-26 17:56 UTC by r0x0d

There were a couple of places were warnings were left behind to warn the users that using `inst.` was now required for some boot options. This patch removes the warnings as it is mandatory to have the prefix for those options.

2024-06-26 17:56 UTC, r0x0d commented
/build-image

2024-06-26 17:57 UTC, r0x0d commented
/kickstart-tests --testtype dracut

2024-06-27 11:01 UTC, KKoukiou requested changes

2024-06-27 11:01 UTC, KKoukiou commented on dracut/parse-anaconda-options.sh
> -    product=$(config_get Main Product < $buildstamp)
Mistake?

2024-06-27 11:01 UTC, KKoukiou commented on dracut/parse-anaconda-options.sh
> -    arg="$(getarg "$1")" && warn_critical "'$1=$arg'" && \
Mistake?

2024-06-27 11:01 UTC, KKoukiou commented on dracut/parse-anaconda-options.sh
> -    if [ "$1" == "--quiet" ]; then quiet=1; shift; fi
Unrelated change?

2024-06-28 10:50 UTC, KKoukiou commented
/kickstart-tests --testtype smoke

2024-06-28 10:52 UTC, KKoukiou commented
/kickstart-tests --testtype dracut

2024-06-28 10:53 UTC, KKoukiou approved these changes
We need to adjust 'dracut-visible-warnings.sh' test in https://github.com/rhinstaller/kickstart-tests/ repository and merge in one go.

2024-07-08 12:37 UTC, r0x0d commented
/kickstart-tests --testtype dracut

2024-07-08 13:45 UTC, r0x0d commented
Kickstart PR: https://github.com/rhinstaller/kickstart-tests/pull/1239

2024-07-11 13:17 UTC, jkonecny12 commented
I wonder, is this something we want to do? These warnings may help people to find out they are doing things wrong. If we turn them off we won't give them any feedback about this.

2024-07-11 13:20 UTC, jkonecny12 commented
@jstodola are you fine with doing this now? I guess it's fine for RHEL-11 to do this?

2024-07-12 11:35 UTC, jstodola commented
Yes, I'm fine with this change.

2024-07-13 13:36 UTC, jkonecny12 approved these changes
In that case, let's make Anaconda a bit lightweight :+1: . Looks great, thanks!

2024-07-13 13:37 UTC, jkonecny12 commented
One more to add. Please add release note for this PR.
https://anaconda-installer.readthedocs.io/en/latest/contributing.html#release-notes

This is important change and we should make it visible.

2024-07-15 12:26 UTC, r0x0d commented
> One more to add. Please add release note for this PR. https://anaconda-installer.readthedocs.io/en/latest/contributing.html#release-notes
> 
> This is important change and we should make it visible.

Alright, will do it right now

2024-07-16 06:51 UTC, KKoukiou reviewed
Please squash :) the 'Add release note' is very generic commit message.

2024-07-22 13:55 UTC, KKoukiou approved these changes

2024-07-25 13:18 UTC, KKoukiou commented
/kickstart-tests --testtype dracut

2024-07-25 13:18 UTC, KKoukiou commented
/kickstart-tests --testtype smoke

2024-08-02 17:17 UTC, r0x0d commented
@KKoukiou, can we remove the "release notes required" tag?

2024-08-05 08:09 UTC, KKoukiou commented
Just rebased.

2024-08-05 08:09 UTC, KKoukiou commented
/kickstart-tests --testtype dracut

2024-08-12 07:10 UTC, KKoukiou commented
/kickstart-tests --testtype dracut

2024-08-12 12:51 UTC, merged