infra: Local image udates workflow  - rhel-10 branch version
rhinstaller/anaconda pull request #5754
Opened 2024-07-10 16:13 UTC by M4rtinK

This is a RHEL 10 version of the local development scripts PR, which should work fine both for Fedora and RHEL 10 development.

Marking as infra due to these scripts having having no impact on anything we ship on RHEL 10.

2024-07-11 07:59 UTC, KKoukiou approved these changes
I see this was merged at two seperate commits on master as well.  But generally when introducing new code - fix up commits should be squashed prior merging.

2024-07-11 10:32 UTC, jkonecny12 requested changes
Please add these files to `.structure-config` file, these are not code related scripts.

2024-07-11 14:21 UTC, M4rtinK commented
> I see this was merged at two seperate commits on master as well. But generally when introducing new code - fix up commits should be squashed prior merging.

Sure, that's how I do this when I do fixup commit myself - in this case I was kinda trying out the Github suggested change functionality. We can certainly use it the same way - add the fixup commit/s to the most relevant existing commit.

I was just thinking that in some cases a separate commit contributed by another user could work as well ? Seems like a good way to give credit for such improvements. Anyway, lets just squash these fixup commits for now. :)

2024-07-11 14:25 UTC, M4rtinK commented
> Please add these files to `.structure-config` file, these are not code related scripts.

Added - should I do that also on the `master` branch ? :)

2024-07-11 15:34 UTC, jkonecny12 commented
> > Please add these files to `.structure-config` file, these are not code related scripts.
> 
> Added - should I do that also on the `master` branch ? :)

Yes please.

2024-07-11 15:41 UTC, jkonecny12 reviewed
Looks good to me otherwise but please fix the path first.

2024-07-11 15:41 UTC, jkonecny12 commented on .structure-config
> +update_boot_iso
Please add it here including the directory as it is line above.

2024-07-11 15:41 UTC, jkonecny12 commented on CONTRIBUTING.rst
> +(on Fedora branches) or CentoOS Stream (on RHEL branches) packages. The script makes sure to remove the old images first
```suggestion
(on Fedora branches) or CentOS Stream (on RHEL branches) packages. The script makes sure to remove the old images first
```

2024-07-15 11:45 UTC, M4rtinK commented on CONTRIBUTING.rst
> +(on Fedora branches) or CentoOS Stream (on RHEL branches) packages. The script makes sure to remove the old images first
Fixed, thanks! :)

2024-07-15 12:09 UTC, jkonecny12 approved these changes

2024-07-15 12:09 UTC, jkonecny12 commented
Thanks!

2024-07-15 14:06 UTC, merged