[RFR]Copied cyrpto policy helper changes to RHEL 9 branch
rhinstaller/anaconda pull request #5928
Opened 2024-10-10 07:53 UTC by anurag03

**Thank you** for your contribution!

Please check that your PR follows these rules:

* [ ] [**Code conventions**](https://anaconda-installer.readthedocs.io/en/latest/contributing.html#code-conventions). tl;dr: Follow PEP8, wrap at 100 chars, and provide docstrings.

* [ ] [**Commit message conventions**](https://anaconda-installer.readthedocs.io/en/latest/commit-log.html). tl;dr: Heading, empty line, longer explanations, all wrapped manually. If in doubt, write a longer commit message with more details.

* [ ] **Tests** pass and cover your changes. You can [run tests locally manually](https://anaconda-installer.readthedocs.io/en/latest/testing.html), or have them run as part of the PR. A team member will have to enable tests manually after inspecting the PR.
  *If you don't know how, ask us for help!*

* [ ] [**Release notes**](https://anaconda-installer.readthedocs.io/en/latest/contributing.html#release-notes) and **docs** if the PR adds something major or changes existing behavior.
  *If you don't know how, ask us for help!*

* [ ] **RHEL** rules: If your PR is for a `rhel-*` branch, pay special attention to commit messages. Make sure **all** commit messages include a line linking the commit to a bug, such as `Resolves: RHEL-123456`. For more information, see [the complete rules](https://anaconda-installer.readthedocs.io/en/latest/commit-log.html).
  *If you don't know how, ask us for help!*

Don't forget - *if you don't know how, ask us for help!*

And now that you read this all, you can delete it and type your own description of your changes :-)

2024-10-10 07:53 UTC, pep8speaks commented
Hello @anurag03! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`tests/unit_tests/pyanaconda_tests/modules/security/test_module_security.py`](https://github.com/rhinstaller/anaconda/blob/395000ae84c3f5f699e08ba1e7597198cb5ab383/tests/unit_tests/pyanaconda_tests/modules/security/test_module_security.py):

> [Line 1042:13](https://github.com/rhinstaller/anaconda/blob/395000ae84c3f5f699e08ba1e7597198cb5ab383/tests/unit_tests/pyanaconda_tests/modules/security/test_module_security.py#L1042): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent

2024-10-10 10:15 UTC, KKoukiou requested changes
Please fix the commit message: See https://github.com/rhinstaller/anaconda/commit/56b0c7cf8667589db2938c9d22b8792194efdb5a other commits like this one for reference.

Just cherry-pick with `git cherry-pick` the upstream commit, and mention in the commit message like in the commit linked the Resolves and Cherry-pick lines.

2024-10-10 10:17 UTC, KKoukiou reviewed
Also we dont generally sign off commits.
Feel free to leave it if you want to.

2024-10-10 10:17 UTC, KKoukiou commented on tests/unit_tests/pyanaconda_tests/modules/security/test_module_security.py
> +            "/usr/libexec/fips-setup-helper",
Please cherry-pick the original commit and you will not need this fixup.

2024-10-17 10:27 UTC, KKoukiou requested changes
You have typo in the commit message.

cyrpto and then a trailing comma, please fix.

Also please use the following convention for linking the RHEL bug. 

Related: RHEL-58667

2024-10-17 10:28 UTC, KKoukiou requested changes
Additionally please just cherry-pick the commit as requested.
This will fix the title of the commit message to be the same like the original.

2024-10-17 11:00 UTC, anurag03 commented
[This is related to cyrpto policy helper changes,](https://github.com/rhinstaller/anaconda/pull/5928/commits/69fe7486f5efa214e5adc828f95f02ad791dc6e9)
cherry-picked from master branch commit: https://github.com/anurag03/anaconda/commit/123d8197707e4c773281f68ab7b9128d6c500342
Related to this issue: https://issues.redhat.com/browse/RHEL-58667

2024-10-17 12:47 UTC, KKoukiou requested changes
Almost there. It's missing the:

Cherry-picked from commit: ...
Related to: RHEL-*

lines.

So how we do backports is:
* Cherry-pick the commit from master branch with `git cherry-pick`
* Amend the commit message with `git commit --am` to contain the two information pointed as missing above. 
Please fix these and it's good to go.

2024-10-17 12:48 UTC, KKoukiou commented
> [This is related to crypto policy helper changes](https://github.com/rhinstaller/anaconda/pull/5928/commits/69fe7486f5efa214e5adc828f95f02ad791dc6e9) cherry-picked from master branch commit: [anurag03@123d819](https://github.com/anurag03/anaconda/commit/123d8197707e4c773281f68ab7b9128d6c500342) Related: [RHEL-58667]

This is not the original commit. Please point the original commit. This is your fork.

2024-11-01 07:06 UTC, KKoukiou reviewed
@anurag03 I force pushed with the suggested commit message changes.

2024-11-01 07:07 UTC, KKoukiou approved these changes

2024-11-01 12:00 UTC, M4rtinK commented
/kickstart-test --testtype smoke

2024-11-01 15:16 UTC, merged