webui: Add isLeaf to deviceData
rhinstaller/anaconda pull request #5958
Opened 2024-10-23 14:20 UTC by adamkankovsky

2024-10-23 15:39 UTC, KKoukiou requested changes

2024-10-23 15:39 UTC, KKoukiou commented on pyanaconda/modules/storage/devicetree/viewer.py
> +        data.isLeaf = device.isLeaf
Is it maybe `data.isLeaf = device.is_leaf`?

2024-10-23 15:39 UTC, KKoukiou commented on pyanaconda/modules/storage/devicetree/viewer.py
> +        data.isLeaf = device.isLeaf
Can you add also maybe a test case at `tests/unit_tests/pyanaconda_tests/modules/storage/test_module_device_tree.py` ?

2024-10-24 10:59 UTC, KKoukiou approved these changes

2024-10-24 11:17 UTC, vojtechtrefny approved these changes

2024-10-25 16:35 UTC, KKoukiou commented
/kickstart-tests --testtype smoke

2024-10-25 17:01 UTC, merged