docs: Collect release notes for F41
rhinstaller/anaconda pull request #5971
Opened 2024-10-31 06:30 UTC by KKoukiou

2024-10-31 12:16 UTC, M4rtinK approved these changes
Looks good to me, thanks! :)

2024-10-31 16:56 UTC, jkonecny12 requested changes
A few notes from my side.

Also I think we should make the lines consistent. Currently every part has different line size. It seems more or less consistent in the rest of the document.

2024-10-31 16:56 UTC, jkonecny12 commented on docs/release-notes.rst
> +
```suggestion

See also:
    - https://github.com/rhinstaller/anaconda/pull/5493
    
```

2024-10-31 16:56 UTC, jkonecny12 commented on docs/release-notes.rst
> +Traditionally Anaconda creates default persistent network profiles (ifcfg files or keyfiles) for every supported wired network device.  We would like to move towards creating profiles only for device
```suggestion
Traditionally Anaconda creates default persistent network profiles (ifcfg files or keyfiles) for every supported wired network device. We would like to move towards creating profiles only for devices explicitly configured by installer. As a step in this direction do not create such files for devices used as ports of a virtual device (for example bond device) configured by installer, unless they were explicitly configured separately (for example in early stage from boot options).
```

2024-11-01 06:50 UTC, KKoukiou commented
> A few notes from my side.
> 
> Also I think we should make the lines consistent. Currently every part has different line size. It seems more or less consistent in the rest of the document.

Done. Good point.

2024-11-01 07:10 UTC, KKoukiou commented
/kickstart-tests --waive docs only

2024-11-01 18:07 UTC, jkonecny12 commented
Seems there is a commit which shouldn't be here. Otherwise it looks good.

2024-11-04 07:05 UTC, KKoukiou commented
> Seems there is a commit which shouldn't be here. Otherwise it looks good.

I was just not rebased.

2024-11-04 09:12 UTC, jkonecny12 approved these changes
LGTM!

2024-11-04 09:12 UTC, jkonecny12 commented
/kickstart-test --waive docs only

2024-11-04 16:12 UTC, merged