Backport support for Wayland-native Anaconda live installer from Fedora
rhinstaller/anaconda pull request #5995
Opened 2024-11-13 16:49 UTC by Conan-Kudo

This pull request backports relevant commits to support the Wayland-native live installer setup for CentOS Stream images.

This is needed for CentOS Hyperscale and CentOS Alternative Images.

Resolves: [RHEL-67390](https://issues.redhat.com/browse/RHEL-67390)

2024-11-14 10:33 UTC, jkonecny12 requested changes
I'm planing to backport these commits to rhel-10 branch. So let's separate these from the PR.

2024-11-14 12:49 UTC, Conan-Kudo commented
Separate what into what? This PR is entirely just a backport set.

2024-11-18 14:54 UTC, jkonecny12 commented
Blocked on this: https://github.com/rhinstaller/anaconda/pull/6000

2024-11-18 15:15 UTC, Conan-Kudo commented
Okay, should I rebase this PR on top of yours?

2024-11-18 15:20 UTC, jkonecny12 commented
> Okay, should I rebase this PR on top of yours?

Ideally wait until it is merged. Hopefully, we got these merged during this week.

2024-11-29 12:36 UTC, pep8speaks commented
Hello @Conan-Kudo! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pyanaconda/ui/gui/__init__.py`](https://github.com/rhinstaller/anaconda/blob/a9c0af942e4cd5b80549d6fec2b559bfa7e94185/pyanaconda/ui/gui/__init__.py):

> [Line 35:1](https://github.com/rhinstaller/anaconda/blob/a9c0af942e4cd5b80549d6fec2b559bfa7e94185/pyanaconda/ui/gui/__init__.py#L35): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

2024-11-29 12:37 UTC, Conan-Kudo commented
@jkonecny12 I've rebased this PR and cherry-picked #6018 from @aleasto too.

2024-12-02 13:39 UTC, jkonecny12 commented
/build-image --live

2024-12-02 13:58 UTC, jkonecny12 commented
I forgot that rhel-10 doesn't support Live ISO builds. That failure is expected. In that case I'll just do a smoke test with standard boot.iso.

2024-12-02 13:58 UTC, jkonecny12 commented
/build-image --boot.iso

2024-12-02 14:56 UTC, jkonecny12 approved these changes
I've done smoke testing and everything looks good to me.

2025-01-14 13:19 UTC, merged